/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArcProgress: typeof import('./src/components/ArcProgress/index.vue')['default']
    ClockProgress: typeof import('./src/components/ClockProgress/index.vue')['default']
    DataText: typeof import('./src/components/DataText/index.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HorizontalProgressBar: typeof import('./src/components/HorizontalProgressBar/index.vue')['default']
    MyModal: typeof import('./src/components/MyModal/index.vue')['default']
    NewCircleTickProgress: typeof import('./src/components/NewCircleTickProgress/index.vue')['default']
    NewLineTickProgress: typeof import('./src/components/NewLineTickProgress/index.vue')['default']
    NewTitleBar: typeof import('./src/components/NewTitleBar/index.vue')['default']
    NormalText: typeof import('./src/components/NormalText/index.vue')['default']
    ProgressButton: typeof import('./src/components/ProgressButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VerticalProgressBar: typeof import('./src/components/VerticalProgressBar/index.vue')['default']
  }
}
